import Dashboard from 'pages/MyPage/Dashboard';

const routes = [
    {
        collapse: true,
        name: 'Dashboards',
        icon: 'ni ni-shop text-primary',
        state: 'dashboardsCollapse',
        views: [
            {
                path: '/dashboard',
                name: 'Dashboard',
                miniName: 'D',
                // component: Dashboard,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/mypage',
                name: 'Dashboard',
                miniName: 'A',
                // component: Alternative,
                component: Dashboard,
                layout: '/admin',
            },
        ],
    },
    {
        collapse: true,
        name: 'Examples',
        icon: 'ni ni-ungroup text-orange',
        state: 'examplesCollapse',
        views: [
            {
                path: '/pricing',
                name: 'Pricing',
                miniName: 'P',
                // component: Pricing,
                component: () => {},
                layout: '/auth',
            },
            {
                path: '/login',
                name: 'Login',
                miniName: 'L',
                // component: Login,
                component: () => {},
                layout: '/auth',
            },
            {
                path: '/register',
                name: 'Register',
                miniName: 'R',
                // component: Register,
                component: () => {},
                layout: '/auth',
            },
            {
                path: '/lock',
                name: 'Lock',
                miniName: 'L',
                // component: Lock,
                component: () => {},
                layout: '/auth',
            },
            {
                path: '/timeline',
                name: 'Timeline',
                miniName: 'T',
                // component: Timeline,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/profile',
                name: 'Profile',
                miniName: 'P',
                // component: Profile,
                component: () => {},
                layout: '/admin',
            },
        ],
    },
    {
        collapse: true,
        name: 'Components',
        icon: 'ni ni-ui-04 text-info',
        state: 'componentsCollapse',
        views: [
            {
                path: '/buttons',
                name: 'Buttons',
                miniName: 'B',
                // component: Buttons,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/cards',
                name: 'Cards',
                miniName: 'C',
                // component: Cards,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/grid',
                name: 'Grid',
                miniName: 'G',
                // component: Grid,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/notifications',
                name: 'Notifications',
                miniName: 'N',
                // component: Notifications,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/icons',
                name: 'Icons',
                miniName: 'I',
                // component: Icons,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/typography',
                name: 'Typography',
                miniName: 'T',
                // component: Typography,
                component: () => {},
                layout: '/admin',
            },
            {
                collapse: true,
                name: 'Multi Level',
                miniName: 'M',
                state: 'multiCollapse',
                views: [
                    {
                        path: '#pablo',
                        name: 'Third level menu',
                        component: () => {},
                        layout: '/',
                    },
                    {
                        path: '#pablo',
                        name: 'Just another link',
                        component: () => {},
                        layout: '/',
                    },
                    {
                        path: '#pablo',
                        name: 'One last link',
                        component: () => {},
                        layout: '/',
                    },
                ],
            },
        ],
    },
    {
        collapse: true,
        name: 'Forms',
        icon: 'ni ni-single-copy-04 text-pink',
        state: 'formsCollapse',
        views: [
            {
                path: '/elements',
                name: 'Elements',
                miniName: 'E',
                // component: Elements,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/components',
                name: 'Components',
                miniName: 'C',
                // component: Components,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/validation',
                name: 'Validation',
                miniName: 'V',
                // component: Validation,
                component: () => {},
                layout: '/admin',
            },
        ],
    },
    {
        collapse: true,
        name: 'Tables',
        icon: 'ni ni-align-left-2 text-default',
        state: 'tablesCollapse',
        views: [
            {
                path: '/tables',
                name: 'Tables',
                miniName: 'T',
                // component: Tables,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/sortable',
                name: 'Sortable',
                miniName: 'S',
                // component: Sortable,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/react-bs-table',
                name: 'React BS Tables',
                miniName: 'RBT',
                // component: ReactBSTables,
                component: () => {},
                layout: '/admin',
            },
        ],
    },
    {
        collapse: true,
        name: 'Maps',
        icon: 'ni ni-map-big text-primary',
        state: 'mapsCollapse',
        views: [
            {
                path: '/google',
                name: 'Google',
                miniName: 'G',
                // component: Google,
                component: () => {},
                layout: '/admin',
            },
            {
                path: '/vector',
                name: 'Vector',
                miniName: 'V',
                // component: Vector,
                component: () => {},
                layout: '/admin',
            },
        ],
    },
    {
        path: '/widgets',
        name: 'Widgets',
        icon: 'ni ni-archive-2 text-green',
        // component: Widgets,
        component: () => {},
        layout: '/admin',
    },
    {
        path: '/charts',
        name: 'Charts',
        icon: 'ni ni-chart-pie-35 text-info',
        // component: Charts,
        component: () => {},
        layout: '/admin',
    },
    {
        path: '/calendar',
        name: 'Calendar',
        icon: 'ni ni-calendar-grid-58 text-red',
        // component: Calendar,
        component: () => {},
        layout: '/admin',
    },
];

export default routes;
